export const TRADE_SELECTED = 'TRADE_SELECTED';

export const FETCH_TRADES_BEGIN   = 'FETCH_TRADES_BEGIN';
export const FETCH_TRADES_SUCCESS = 'FETCH_TRADES_SUCCESS';
export const FETCH_TRADES_FAILURE = 'FETCH_TRADES_FAILURE';