
export const SAVE_TRADE_BEGIN   = 'SAVE_TRADE_BEGIN';
export const SAVE_TRADE_SUCCESS = 'SAVE_TRADE_SUCCESS';
export const SAVE_TRADE_FAILURE = 'SAVE_TRADE_FAILURE';
export const SAVE_TRADE_STATUS_CLEAR ='SAVE_TRADE_STATUS_CLEAR';